### ISSUE TITLE
JRuby 1.7.20 - Cannot install lotus-utils

### ISSUE THREAD

**Issue by Sdogruyol** [lotus/lotus#236]
lotus-utils cannot be installed on JRuby 1.7.20

Here's the stacktrace.

```
ERROR:  Error installing lotus-utils:
	lotus-utils requires Ruby version >= 2.0.0.
```

That's because 

```
jruby-1.7.20 :001 > RUBY_VERSION
 => "1.9.3"
```

Shall we support anything other than JRuby 9k? //cc @jodosha

**Comment by joneslee85** [comment]
@Sdogruyol does this version support `prepend` yet?

**Comment by Sdogruyol** [comment]
@joneslee85 well i guess i doesn't support ```prepent```

Here's a quick demo

```
jruby-1.7.20 :009 > module Prepender
jruby-1.7.20 :010?>   end
 => nil
jruby-1.7.20 :011 > class SomeClass
jruby-1.7.20 :012?>   prepend Prepender
jruby-1.7.20 :013?>   end
NoMethodError: undefined method `prepend' for SomeClass:Class
	from (irb):12:in `SomeClass'
	from (irb):11:in `evaluate'
	from org/jruby/RubyKernel.java:1111:in `eval'
	from org/jruby/RubyKernel.java:1511:in `loop'
	from org/jruby/RubyKernel.java:1274:in `catch'
	from org/jruby/RubyKernel.java:1274:in `catch'
	from /Users/serdardogruyol/.rvm/rubies/jruby-1.7.20/bin/irb:13:in `(root)'
```

**Comment by deepj** [comment]
Unfortunately, `prepend` is in JRuby since 9.0.0.0 => https://github.com/jruby/jruby/issues/751

So Lotus doesn't work with JRuby 1.7 at all and won't be anymore.

**Comment by jodosha** [comment]
@Sdogruyol @deepj @joneslee85 Lotus only targets Ruby 2+. That means MRI and all the other VMs that have the same features. JRuby 1.7 is out of scope. :smile_cat:
